### ISSUE TITLE
Make the "one line of code"-snippet actual code?

### ISSUE THREAD

**Issue by Malvoz** [oysterprotocol/website#31]
The first thing I noticed when I stumbled upon Oyster was that the "Revenue, in One Line of Code"-snippet wasn't actual code. 

I think it would be beneficial both to the Oyster team and its customers to have actual code.<br> _Code that Can Be Copied in a Single Click_. 😆

### Try it out

Go to https://oysterprotocol.com/, open dev tools and replace <br>`<img class="code" src="assets/img/Code.png">` with:

```
<style>
.oyster-script {
  margin: 0 auto 5rem auto;
  max-width: 700px;
  padding: 1rem;
  background-color: transparent;
  -webkit-user-select: all; /* Make the code copyable in 1 click. */
     -moz-user-select: all;
      -ms-user-select: all;
          user-select: all;
}

.oyster-script code {
  font-size: 1.75rem;
  padding: 1rem;
  background-color: #222;
  display: block;
  border-radius: 4px; 
  -webkit-box-shadow: 0 -3px 44px 0 rgba(0, 0, 0, 0.03), 0 36px 43px 0 rgba(0, 0, 0, 0.2);
          box-shadow: 0 -3px 44px 0 rgba(0, 0, 0, 0.03), 0 36px 43px 0 rgba(0, 0, 0, 0.2);
  color: #deeaa2;
  overflow-y: auto;
}

</style> 
<blockquote class="oyster-script">
<code>
&lt;script id="o.ws" payout="ETH_ADDRESS" src="https://oyster.ws/webnode.js"&gt;&lt;/script&gt;
</code>
</blockquote>
```

WDYT?

**Comment by AaronVasquez** [comment]
Thanks @Malvoz, our webnode js code isn't ready yet to be copied onto real sites right now, but we are working on it!

**Comment by jfarago** [comment]
@AaronVasquez you want to close this out?
